central = {	'BNK': 'Bank',
			'CHG': 'Chigwell',
			'CYL': 'Chancery Lane',
			'DEB': 'Debden',
			'EAC': 'East Acton',
			'EBY': 'Ealing Broadway',
			'EPP': 'Epping',
			'FLP': 'Fairlop',
			'GFD': 'Greenford',
			'GHL': 'Gants Hill',
			'GRH': 'Grange Hill',
			'HAI': 'Hainault',
			'HLN': 'Hanger Lane',
			'HOL': 'Holborn',
			'HPK': 'Holland Park',
			'LAN': 'Lancaster Gate',
			'LEY': 'Leyton',
			'LST': 'Liverpool Street',
			'LTN': 'Loughton',
			'LYS': 'Leytonstone',
			'MAR': 'Marble Arch',
			'MLE': 'Mile End',
			'NAC': 'North Acton',
			'NEP': 'Newbury Park',
			'NHG': 'Notting Hill Gate',
			'NHT': 'Northolt',
			'OXC': 'Oxford Circus',
			'PER': 'Perivale',
			'QWY': 'Queensway',
			'RED': 'Redbridge',
			'ROD': 'Roding Valley',
			'RUG': 'Ruislip Gardens',
			'SBC': 'Shepherd\'s Bush',
			'SFD': 'Stratford',
			'SNB': 'Snaresbrook',
			'SRP': 'South Ruislip',
			'STP': 'St Paul\'s',
			'SWF': 'South Woodford',
			'TCR': 'Tottenham Court Road',
			'THB': 'Theydon Bois',
			'WAC': 'West Acton',
			'WAN': 'Wanstead',
			'WCT': 'White City',
			'WFD': 'Woodford',
			'WRP': 'West Ruislip'
		}
district = {
			'WBT': 'West Brompton', 
			'EPY': 'East Putney', 
			'BEC': 'Becontree', 
			'RCP': 'Ravenscourt Park', 
			'GUN': 'Gunnersbury', 
			'WDN': 'Wimbledon', 
			'ERD': 'Edgware Road (H & C)', 
			'UPM': 'Upminster', 
			'PAD': ' Paddington Circle (undocumented)', 
			'EPK': 'Elm Park', 
			'ACT': 'Acton Town', 
			'BCT': 'Barons Court', 
			'SKN': 'South Kensington',
			'UPK': 'Upton Park', 
			'TGR': 'Turnham Green', 
			'BWR': 'Bow Road', 
			'BKG': 'Barking', 
			'TEM': 'Temple', 
			'DGE': 'Dagenham East', 
			'WHM': 'West Ham', 
			'ECM': 'Ealing Common', 
			'EMB': 'Embankment', 
			'ECT': 'Earl\'s Court', 
			'PGR': 'Parsons Green',
			'BLF': 'Blackfriars', 
			'HMD': 'Hammersmith (District and Picc)', 
			'OLY': 'Olympia', 
			'STG': 'Stepney Green', 
			'HST': 'High Street Kensington', 
			'STB': 'Stamford Brook', 
			'MLE': 'Mile End', 
			'WMS': 'Westminster', 
			'SJP': "St. James's Park", 'WMP': 'Wimbledon Park', 
			'UPB': 'Upminster Bridge', 
			'BBB': 'Bromley-by-Bow', 
			'CHP': 'Chiswick Park',
			'PUT': 'Putney Bridge', 
			'GRD': 'Gloucester Road', 
			'THL': 'Tower Hill', 
			'UPY': 'Upney', 
			'CST': 'Cannon Street', 
			'HCH': 'Hornchurch', 
			'EHM': 'East Ham', 
			'WCL': 'Whitechapel', 
			'PLW': 'Plaistow', 
			'VIC': 'Victoria', 
			'WKN': 'West Kensington', 
			'FBY': 'Fulham Broadway', 
			'ALE': 'Aldgate East', 
			'SSQ': 'Sloane Square', 
			'SFS': 'Southfields', 
			'EBY': 'Ealing Broadway', 
			'RMD': 'Richmond', 
			'MON': 'Monument', 
			'KEW': 'Kew Gardens', 
			'DGH': 'Dagenham Heathway', 
			'MAN': 'Mansion House'
		}
hammersmith_city = circle = {
			'ALD': 'Aldgate',
			'ALE': 'Aldgate East',
			'BAR': 'Barbican',
			'BAY': 'Bayswater (undocumented)',
			'BBB': 'Bromley-by-Bow',
			'BKG': 'Barking',
			'BLF': 'Blackfriars',
			'BST': 'Baker Street',
			'BWR': 'Bow Road',
			'CST': 'Cannon Street',
			'EHM': 'East Ham',
			'EMB': 'Embankment',
			'ERD': 'Edgware Road (H & C)',
			'ESQ': 'Euston Square',
			'FAR': 'Farringdon',
			'GPS': 'Great Portland Street',
			'GRD': 'Gloucester Road',
			'HMS': 'Hammersmith',
			'HST': 'High Street Kensington',
			'KXX': "King's Cross St Pancras",
			'LBG': 'Ladbroke Grove (undocumented)',
			'LST': 'Liverpool Street',
			'MAN': 'Mansion House',
			'MGT': 'Moorgate',
			'MLE': 'Mile End',
			'MON': 'Monument',
			'NHG': 'Notting Hill Gate (undocumented)',
			'PAD': ' Paddington H & C (undocumented)',
			'PLW': 'Plaistow',
			'ROA': 'Royal Oak (undocumented)',
			'SJP': "St. James's Park",
			'SKN': 'South Kensington',
			'SSQ': 'Sloane Square',
			'STG': 'Stepney Green',
			'TEM': 'Temple',
			'THL': 'Tower Hill',
			'UPK': 'Upton Park',
			'VIC': 'Victoria',
			'WBP': 'Westbourne Park (undocumented)',
			'WCL': 'Whitechapel',
			'WHM': 'West Ham',
			'WMS': 'Westminster'
		}

jubilee = {
			'BDS': 'Bond Street',
			'BER': 'Bermondsey',
			'BST': 'Baker Street',
			'CHX': 'Charing Cross (undocumented)',
			'CNT': 'Canning Town',
			'CPK': 'Canons Park',
			'CWF': 'Canary Wharf',
			'CWR': 'Canada Water',
			'DHL': 'Dollis Hill',
			'FRD': 'Finchley Road',
			'GPK': 'Green Park',
			'KBY': 'Kingsbury',
			'KIL': 'Kilburn',
			'LON': 'London Bridge',
			'NEA': 'Neasden',
			'NGW': 'North Greenwich',
			'QBY': 'Queensbury',
			'SFD': 'Stratford',
			'SJW': 'St John\'s Wood',
			'STA': 'Stanmore',
			'SWC': 'Swiss Cottage',
			'SWK': 'Southwark',
			'WHD': 'West Hampstead',
			'WHM': 'West Ham',
			'WLG': 'Willesden Green',
			'WLO': 'Waterloo',
			'WMS': 'Westminster',
			'WPK': 'Wembley Park'
		}

metropolitan = {
			'ALD': 'Aldgate',
			'AME': 'Amersham',
			'BAR': 'Barbican',
			'BKG': 'Barking (undocumented)',
			'BST': 'Baker Street',
			'CLF': 'Chalfont and Latimer',
			'CLW': 'Colliers Wood',
			'CRX': 'Croxley',
			'CWD': 'Chorleywood',
			'ESQ': 'Euston Square',
			'ETE': 'Eastcote',
			'FAR': 'Farringdon',
			'FRD': 'Finchley Road',
			'GPS': 'Great Portland Street',
			'HDN': 'Hillingdon',
			'HOH': 'Harrow on the Hill',
			'ICK': 'Ickenham',
			'KXX': "King's Cross St Pancras",
			'LST': 'Liverpool Street',
			'MGT': 'Moorgate',
			'MPK': 'Moor Park',
			'NHR': 'North Harrow',
			'NWD': 'Northwood',
			'NWH': 'Northwood Hills',
			'NWP': 'Northwick Park',
			'PIN': 'Pinner',
			'RKY': 'Rickmansworth',
			'RLN': 'Rayners Lane',
			'RUI': 'Ruislip',
			'RUM': 'Ruislip Manor',
			'UXB': 'Uxbridge',
			'WAT': 'Watford',
			'WCL': 'Whitechapel (undocumented)',
			'WHR': 'West Harrow',
			'WPK': 'Wembley Park',
			'WSP': 'Woodside Park (undocumented)'
		}

nothern = {
			'ALD': 'Aldgate',
			'AME': 'Amersham',
			'BAR': 'Barbican',
			'BKG': 'Barking (undocumented)',
			'BST': 'Baker Street',
			'CLF': 'Chalfont and Latimer',
			'CLW': 'Colliers Wood',
			'CRX': 'Croxley',
			'CWD': 'Chorleywood',
			'ESQ': 'Euston Square',
			'ETE': 'Eastcote',
			'FAR': 'Farringdon',
			'FRD': 'Finchley Road',
			'GPS': 'Great Portland Street',
			'HDN': 'Hillingdon',
			'HOH': 'Harrow on the Hill',
			'ICK': 'Ickenham',
			'KXX': "King's Cross St Pancras",
			'LST': 'Liverpool Street',
			'MGT': 'Moorgate',
			'MPK': 'Moor Park',
			'NHR': 'North Harrow',
			'NWD': 'Northwood',
			'NWH': 'Northwood Hills',
			'NWP': 'Northwick Park',
			'PIN': 'Pinner',
			'RKY': 'Rickmansworth',
			'RLN': 'Rayners Lane',
			'RUI': 'Ruislip',
			'RUM': 'Ruislip Manor',
			'UXB': 'Uxbridge',
			'WAT': 'Watford',
			'WCL': 'Whitechapel (undocumented)',
			'WHR': 'West Harrow',
			'WPK': 'Wembley Park',
			'WSP': 'Woodside Park (undocumented)'
		}

picadilly = {
			'HNC': 'Hounslow Central', 
			'HNE': 'Hounslow East', 
			'HNW': 'Hounslow West', 
			'COV': 'Covent Garden', 
			'WGN': 'Wood Green', 
			'BOS': 'Boston Manor', 
			'OAK': 'Oakwood', 
			'NEL': 'North Ealing', 
			'SGT': 'Southgate', 
			'BGR': 'Bounds Green', 
			'CRD': 'Caledonian Road', 
			'ETE': 'Eastcote', 
			'BCT': 'Barons Court', 
			'HDN': 'Hillingdon', 
			'SKN': 'South Kensington', 
			'AGR': 'Arnos Grove', 
			'TGR': 'Turnham Green', 
			'KXX': "King's Cross St Pancras", 'TPL': 'Turnpike Lane', 
			'MNR': 'Manor House', 
			'ECM': 'Ealing Common', 
			'PIC': 'Piccadilly Circus', 
			'OST': 'Osterley', 
			'ECT': 'Earl\'s Court', 
			'UXB': 'Uxbridge', 
			'LSQ': 'Leicester Square', 
			'HMD': 'Hammersmith (District and Picc)', 
			'SEL': 'South Ealing', 
			'PRY': 'Park Royal', 
			'STN': 'Sudbury Town', 
			'ICK': 'Ickenham', 
			'SHR': 'South Harrow', 
			'NFD': 'Northfields', 
			'GPK': 'Green Park', 
			'HOL': 'Holborn', 
			'HRV': 'Heathrow Terminal 5', 
			'KNB': 'Knightsbridge', 
			'FPK': 'Finsbury Park', 
			'GRD': 'Gloucester Road', 
			'RUI': 'Ruislip', 
			'HPC': 'Hyde Park Corner', 
			'HRD': 'Holloway Road', 
			'SHL': 'Sudbury Hill', 
			'HRC': 'Heathrow Terminals 123', 
			'HTF': 'Heathrow Terminal 4', 
			'RLN': 'Rayners Lane', 
			'RUM': 'Ruislip Manor', 
			'RSQ': 'Russell Square', 
			'ACT': 'Acton Town', 
			'ARL': 'Arsenal', 
			'CFS': 'Cockfosters', 
			'ALP': 'Alperton', 
			'HTX': 'Hatton Cross'
		}

victoria = {
			'BHR': 'Blackhorse Road',
			'BRX': 'Brixton',
			'EUS': 'Euston',
			'FPK': 'Finsbury Park',
			'GPK': 'Green Park',
			'HBY': 'Highbury and Islington',
			'KXX': "King's Cross St Pancras",
			'OXC': 'Oxford Circus',
			'PIM': 'Pimlico',
			'STK': 'Stockwell',
			'SVS': 'Seven Sisters',
			'TTH': 'Tottenham Hale',
			'VIC': 'Victoria',
			'VUX': 'Vauxhall',
			'WAL': 'Walthamstow Central',
			'WST': 'Warren Street'
		}

waterloo_city = {
			'BNK': 'Bank',
			'WLO': 'Waterloo'
		}